language: java
jdk:
  - oraclejdk8
install: true
notifications:
  email: 
  on_success: never
  on_failure: always
deploy:
  provider: releases
  api_key:
    secure: LBiChESWSXl7cz9bpnvQmd1HUbYTvQcVWxI98jbn86FZ8KH6RsnLxmjw2ycQM0C4xlDi4w0FijqgOSnuNfEm6gQ3+oAj6wxAkT/Xk8gzbXZ11wvWma5Y7dVXfqMOClWCnCfiNkrqVfoCHfURYKyfhS0bKVdUv5/KX88LtfRb0TA72fJijec1EnNMBgYWrJ4P/R382Gjx7T4YkjlyZoExjFMUoMPkdubxki+oYanvEI0Y6OoATYkFFsoo8zMeNEY5o7frJ5Tkvp03moAtAmhwXxBOVIxCoBu7ck7A6oAiJyj1wPpfOHzvdRmVlL6sFvpIDWCuGWFFOzXzpJj5B8hB6pceI2mcNDKl9ejKL3vq0sH8MWSANMLOfBHyhMxnvbub7PWwm5DzjZFI6Y3AlzePF04arUJ/Ix6KrSYLXFzRra3YvA3B7MoTzQTFwuvS1iuTZUPDX3jw+6+78knOA0u6/DsH/CFUcAEzXmooigg0l850rRGAMfRG53tn8ijDT0p/u5i7AW0C5Yc9DscZZz5JAyk66I/BbiEF88VOQ7Wa1RZiBJEYLtfoDsCAAa0s0r1xKryGVCj1W7ew1IAQC+S+RkoLVXUn1qeUsuMnnVav67tgSGoiK3ICCGVv2uErPw8bXYij6cKxL07o/I13cHXmiPepEGTGRGp8sMtONG12rYI=
  skip_cleanup: true
  file_glob: true
  file: target/scraper*.jar
  on:
    tags: true
    repo: SBI-/BoardScraper

env:
  global:
   # The next declaration is the encrypted COVERITY_SCAN_TOKEN, created
   #   via the "travis encrypt" command using the project repo's public key
   - secure: "HJXAK0BY4F44SiObmFbsftR9AJlc4ePNcZzUwGB9zshulw90W0aSVW7ryR/SKvYIZp1pDDowssEVVYkv9Yhd0bIGPjmDJTV+1mhSFgdfOZ1bkN46MjXL9h1GmXSWOoMG5T66h3NXAmxCUxEUvfPHjxI520nMFQzW58Xaz5JngyOvJsgryANEyGeBlRV5zfXdbZuCJhMZcdUx3tDmcomPhA/HVOCvPzSn12R2y+BiV7ggoXXgCmz2Z6UT4NNfodxVMyd5+LWztRXntmCFnkOG3CWDY7Bt3KDxeqvgUhbtJea1tVJwZ01fySk6Kks2kb4uYDD7gr87IyCsZtCTVmH9XMk0Q4WM4cNJGPjvS+v6st66m0ndXBP6MToJ+L3ex+giijRqVc8KmZaTH4o+04sBrYilGI8MAxQt5TOy1CnDCTKT02ApAtmTn+SfZRcsttmd4zcUfoQb4ENTaaW7Elwcw7DkJWfkEpmqbnUMTfh6EEv+pqBZV4ZUcYb3aYE2hRizWMOmSsUWN9ms2hRM6+9/gT01EuuIa6htCOgH9DHD1U9Jn69DAukit0nWgU1YG/8DRA//rrfQ3HJIVru/xT4TUbzxylF935m4BOTo7wZiorFSStr6xyj9p7bX3g6hkXpLYLGWVY8KOQFSe/clCMz//bvYiGSqMWmYeXEqOYk95BM="

before_install:
      - echo -n | openssl s_client -connect scan.coverity.com:443 | sed -ne '/-BEGIN CERTIFICATE-/,/-END CERTIFICATE-/p' | sudo tee -a /etc/ssl/certs/ca-

addons:
  coverity_scan:
    project:
      name: "SBI-/BoardScraper"
      description: "Build submitted via Travis CI"
    build_command_prepend: "mvn clean"
    build_command:   "mvn -DskipTests=true compile"
    branch_pattern: coverity_scan
